# $Id: Makefile,v 1.0 2022/10/31 11:29:30 pyr Exp $

TRUEPREFIX?=	/usr/local

BINDIR 	=	${TRUEPREFIX}/bin
MANDIR	=	${TRUEPREFIX}/man/cat
PROG	=	ipcalc
CFLAGS	+=	-Wall -Werror -Wstrict-prototypes -g3

.include <bsd.prog.mk>
